"use strict";var h=Object.defineProperty;var I=Object.getOwnPropertyDescriptor;var T=Object.getOwnPropertyNames;var E=Object.prototype.hasOwnProperty;var R=(i,r,t)=>r in i?h(i,r,{enumerable:!0,configurable:!0,writable:!0,value:t}):i[r]=t;var $=(i,r)=>{for(var t in r)h(i,t,{get:r[t],enumerable:!0})},O=(i,r,t,e)=>{if(r&&typeof r=="object"||typeof r=="function")for(let n of T(r))!E.call(i,n)&&n!==t&&h(i,n,{get:()=>r[n],enumerable:!(e=I(r,n))||e.enumerable});return i};var k=i=>O(h({},"__esModule",{value:!0}),i);var u=(i,r,t)=>R(i,typeof r!="symbol"?r+"":r,t);var L={};$(L,{default:()=>F});module.exports=k(L);var C=require("@libs/defaultCover"),g=require("@libs/fetch"),c=require("@libs/novelStatus"),N=require("@nekori/cookie");var y={UNSPECIFIED:0,SAFE:1,MIXED:2,NSFW:3},P={NOVEL:"novel",IMAGE:"image",VIDEO:"video",MIXED:"mixed"};var d=class{constructor(){u(this,"contentType",P.NOVEL);u(this,"contentWarning",y.UNSPECIFIED);u(this,"minApiVersion",1);u(this,"outputTarget","js");u(this,"isNekoriPlugin",!0)}resolveUrl(r,t){return this.site+r}};var w=require("@nekori/utils"),f=require("cheerio"),b=class extends d{constructor(){super(...arguments);this.id="tieuthuyetmang.com";this.name="Tiểu Thuyết Mạng";this.icon="icon.png";this.site="https://tieuthuyetmang.com";this.version="1.1.0";this.imageRequestInit={headers:{Referer:this.site}};this.filters=void 0}beforeRequest(){return(0,N.set)(this.site,{name:"site_access_gate",value:"1",path:"/",httpOnly:!0,secure:!0})}normalizeCoverUrl(t){if(!t)return C.defaultCover;try{let e=new URL(t,this.site);if(e.pathname.startsWith("/_next/image")){let n=e.searchParams.get("url");if(n)return new URL(decodeURIComponent(n),this.site).toString()}return e.toString()}catch{return t}}normalizeNovelPath(t){if(!t)return t;try{let e=new URL(t,this.site);return e.pathname=e.pathname.replace(/\/nghe\/\d+\/?$/,""),e.pathname}catch{return t}}normalizeStatus(t){let e=t.toLowerCase();return e.includes("hoàn")?c.NovelStatus.Completed:e.includes("tạm")?c.NovelStatus.OnHiatus:e.includes("đang")||e.includes("tiến hành")?c.NovelStatus.Ongoing:c.NovelStatus.Unknown}normalizeEscapedJson(t){return t.replace(/\\"/g,'"').replace(/\\n/g,`
`).replace(/\\r/g,"\r").replace(/\\t/g,"	").replace(/\\\\/g,"\\")}parseChaptersFromHtml(t,e){let n=t.match(/\\"chapters\\":\[(.*?)\],\\"contentDescription\\"/s),s=t.match(/"chapters":\[(.*?)\],"contentDescription"/s),a=null;if(n?.[1]?a=`[${this.normalizeEscapedJson(n[1])}]`:s?.[1]&&(a=`[${s[1]}]`),!a)return[];let o;try{o=JSON.parse(a)}catch{return[]}return o.map(l=>({chapterNumber:l.chapterNumber,name:`${l.isLocked?"🔒 ":"📖 "}Chương ${l.chapterNumber}: ${l.title}`,path:`${e}/doc/${l.chapterNumber}`})).sort((l,p)=>l.chapterNumber-p.chapterNumber)}async popularNovels(t,e){let s=await(await(0,g.fetchApi)(`https://be.tieuthuyetmang.com/api/stories?sort=hot&page=${t}&per_page=20`)).json(),a=[];return s.data.forEach(o=>{!o.slug||!o.title||a.push({name:o.title,path:`/truyen/${o.slug}`,cover:this.normalizeCoverUrl(o.coverUrl)})}),a}async parseNovel(t){await this.beforeRequest();let e=await(0,g.fetchApi)(new URL(t,this.site).toString());if(!e.ok)throw new Error(`Failed to fetch novel page: ${e.status} ${e.statusText}`);let n=await e.text(),s=(0,f.load)(n),a=s("h1").first().text().trim(),o=s(".prose").text().trim()||"",l=s("h1").next("div").find("span").first().text().trim()||s("span").filter((U,v)=>s(v).text().toLowerCase().includes("trạng thái")).first().text().trim(),p=s("h1").next("div").find("span").slice(1).map((U,v)=>s(v).text().trim()).get().filter(Boolean).join(","),m=s('a[href*="/tac-gia/"]').first().text().trim(),x=s("h1").closest("div.flex-1.min-w-0").prev().find("img").first().attr("src"),S=this.parseChaptersFromHtml(n,t);return{path:this.normalizeNovelPath(t),name:a||"Untitled",cover:this.normalizeCoverUrl(x),summary:o,author:m,genres:p,status:l?this.normalizeStatus(l):c.NovelStatus.Unknown,chapters:S}}async parseChapter(t){await this.beforeRequest();let n=await(await(0,g.fetchApi)(new URL(t,this.site).toString())).text(),a=(0,f.load)(n)(".whitespace-pre-wrap").first();if(!a?.text().trim())throw new Error("Không thể tải nội dung chương này. Hãy thử đăng nhập WebView trước.");return{state:"ready",type:"novel",html:`<div>${a.html()?.trim().split(`
`).map(o=>`<p>${(0,w.encodeHtmlEntities)(o)}</p>`).join("<br>")}<div>`}}async searchNovels(t,e){if(!t.trim()||e>1)return[];let n=new URL("https://be.tieuthuyetmang.com/api/search");n.searchParams.set("q",t);let a=await(await(0,g.fetchApi)(n.toString())).json(),o=[];return(a.stories||[]).forEach(l=>{let p=l.slug?.trim(),m=l.title?.trim();!p||!m||o.push({name:m,path:`/truyen/${p}`,cover:this.normalizeCoverUrl(l.coverUrl)})}),o}resolveUrl(t,e){return this.site+t}},F=new b;
;if(module.exports.default)exports.default=(function resolvePluginAssets(plugin) {
  for (const field of ['icon', 'customCSS', 'customJS']) {
    const value = plugin[field];
    if (typeof value === 'string' && value && !value.includes('/')) {
      plugin[field] = `src/${plugin.id}/${value}`;
    }
  }
  return plugin;
})(module.exports.default);
