import { type Filters, FilterTypes } from '@libs/filterInputs';

export default {
  sort_lang: {
    type: FilterTypes.Picker,
    label: 'Phiên bản',
    value: '',
    options: [
      { label: 'Tất cả', value: '' },
      { label: 'Phụ đề (Vietsub)', value: 'vietsub' },
      { label: 'Thuyết Minh', value: 'thuyet-minh' },
      { label: 'Lồng Tiếng', value: 'long-tieng' },
    ],
  },
  category: {
    type: FilterTypes.Picker,
    label: 'Thể loại',
    value: '',
    options: [
      { label: 'Tất cả', value: '' },
      { label: 'Hành Động', value: 'hanh-dong' },
      { label: 'Miền Tây', value: 'mien-tay' },
      { label: 'Trẻ Em', value: 'tre-em' },
      { label: 'Lịch Sử', value: 'lich-su' },
      { label: 'Cổ Trang', value: 'co-trang' },
      { label: 'Chiến Tranh', value: 'chien-tranh' },
      { label: 'Viễn Tưởng', value: 'vien-tuong' },
      { label: 'Kinh Dị', value: 'kinh-di' },
      { label: 'Tài Liệu', value: 'tai-lieu' },
      { label: 'Bí Ẩn', value: 'bi-an' },
      { label: 'Phim 18+', value: 'phim-18' },
      { label: 'Tình Cảm', value: 'tinh-cam' },
      { label: 'Tâm Lý', value: 'tam-ly' },
      { label: 'Thể Thao', value: 'the-thao' },
      { label: 'Phiêu Lưu', value: 'phieu-luu' },
      { label: 'Âm Nhạc', value: 'am-nhac' },
      { label: 'Gia Đình', value: 'gia-dinh' },
      { label: 'Học Đường', value: 'hoc-duong' },
      { label: 'Hài Hước', value: 'hai-huoc' },
      { label: 'Hình Sự', value: 'hinh-su' },
      { label: 'Võ Thuật', value: 'vo-thuat' },
      { label: 'Khoa Học', value: 'khoa-hoc' },
      { label: 'Thần Thoại', value: 'than-thoai' },
      { label: 'Chính Kịch', value: 'chinh-kich' },
      { label: 'Kinh Điển', value: 'kinh-dien' },
    ],
  },
  country: {
    type: FilterTypes.Picker,
    label: 'Quốc gia',
    value: '',
    options: [
      { label: 'Tất cả', value: '' },
      { label: 'Việt Nam', value: 'viet-nam' },
      { label: 'Trung Quốc', value: 'trung-quoc' },
      { label: 'Thái Lan', value: 'thai-lan' },
      { label: 'Hồng Kông', value: 'hong-kong' },
      { label: 'Pháp', value: 'phap' },
      { label: 'Đức', value: 'duc' },
      { label: 'Hà Lan', value: 'ha-lan' },
      { label: 'Mexico', value: 'mexico' },
      { label: 'Thụy Điển', value: 'thuy-dien' },
      { label: 'Philippines', value: 'philippines' },
      { label: 'Đan Mạch', value: 'dan-mach' },
      { label: 'Thụy Sĩ', value: 'thuy-si' },
      { label: 'Ukraina', value: 'ukraina' },
      { label: 'Hàn Quốc', value: 'han-quoc' },
      { label: 'Âu Mỹ', value: 'au-my' },
      { label: 'Ấn Độ', value: 'an-do' },
      { label: 'Canada', value: 'canada' },
      { label: 'Tây Ban Nha', value: 'tay-ban-nha' },
      { label: 'Indonesia', value: 'indonesia' },
      { label: 'Ba Lan', value: 'ba-lan' },
      { label: 'Malaysia', value: 'malaysia' },
      { label: 'Bồ Đào Nha', value: 'bo-dao-nha' },
      { label: 'UAE', value: 'uae' },
      { label: 'Châu Phi', value: 'chau-phi' },
      { label: 'Ả Rập Xê Út', value: 'a-rap-xe-ut' },
      { label: 'Nhật Bản', value: 'nhat-ban' },
      { label: 'Đài Loan', value: 'dai-loan' },
      { label: 'Anh', value: 'anh' },
      { label: 'Quốc Gia Khác', value: 'quoc-gia-khac' },
      { label: 'Thổ Nhĩ Kỳ', value: 'tho-nhi-ky' },
      { label: 'Nga', value: 'nga' },
      { label: 'Úc', value: 'uc' },
      { label: 'Brazil', value: 'brazil' },
      { label: 'Ý', value: 'y' },
      { label: 'Na Uy', value: 'na-uy' },
      { label: 'Nam Phi', value: 'nam-phi' },
    ],
  },
  type: {
    type: FilterTypes.Picker,
    label: 'Loại phim',
    value: '',
    options: [
      { label: 'Tất cả', value: '' },
      { label: 'Phim Lẻ', value: 'phim-le' },
      { label: 'Phim Bộ', value: 'phim-bo' },
      { label: 'TV Shows', value: 'tv-shows' },
      { label: 'Hoạt Hình', value: 'hoat-hinh' },
    ],
  },
  year: {
    type: FilterTypes.Picker,
    label: 'Năm sản xuất',
    value: '',
    options: [
      { label: 'Tất cả', value: '' },
      { label: '2026', value: '2026' },
      { label: '2025', value: '2025' },
      { label: '2024', value: '2024' },
      { label: '2023', value: '2023' },
      { label: '2022', value: '2022' },
      { label: '2021', value: '2021' },
      { label: '2020', value: '2020' },
      { label: '2019', value: '2019' },
      { label: '2018', value: '2018' },
      { label: '2017', value: '2017' },
      { label: '2016', value: '2016' },
      { label: '2015', value: '2015' },
      { label: '2014', value: '2014' },
      { label: '2013', value: '2013' },
      { label: '2012', value: '2012' },
      { label: '2011', value: '2011' },
      { label: '2010', value: '2010' },
    ],
  },
  sort_field: {
    type: FilterTypes.Picker,
    label: 'Sắp xếp',
    value: 'modified.time',
    options: [
      { label: 'Mới cập nhật', value: 'modified.time' },
      { label: 'Thời gian đăng', value: 'created.time' },
      { label: 'Năm sản xuất', value: 'year' },
    ],
  },
} satisfies Filters;
