"use strict";var b=Object.defineProperty;var R=Object.getOwnPropertyDescriptor;var D=Object.getOwnPropertyNames;var j=Object.prototype.hasOwnProperty;var A=(e,t,n)=>t in e?b(e,t,{enumerable:!0,configurable:!0,writable:!0,value:n}):e[t]=n;var L=(e,t)=>{for(var n in t)b(e,n,{get:t[n],enumerable:!0})},V=(e,t,n,r)=>{if(t&&typeof t=="object"||typeof t=="function")for(let o of D(t))!j.call(e,o)&&o!==n&&b(e,o,{get:()=>t[o],enumerable:!(r=R(t,o))||r.enumerable});return e};var _=e=>V(b({},"__esModule",{value:!0}),e);var g=(e,t,n)=>A(e,typeof t!="symbol"?t+"":t,n);var Y={};L(Y,{default:()=>G});module.exports=_(Y);var S=require("@libs/defaultCover"),E=require("@libs/fetch"),N=require("@libs/filterInputs"),h=require("@libs/isAbsoluteUrl"),W=require("@libs/novelStatus");var f={UNSPECIFIED:0,SAFE:1,MIXED:2,NSFW:3},d={NOVEL:"novel",IMAGE:"image",VIDEO:"video",MIXED:"mixed"};var P=class{constructor(){g(this,"contentType",d.NOVEL);g(this,"contentWarning",f.UNSPECIFIED);g(this,"minApiVersion",1);g(this,"outputTarget","js");g(this,"isNekoriPlugin",!0)}resolveUrl(t,n){return this.site+t}};var y=require("@nekori/utils"),m=require("cheerio"),l="https://cosplaytele.com",C="#cosplaytele-photos",$="#cosplaytele-video",M=[{label:"All",value:""},{label:"Cosplay Nude",value:`${l}/category/nude/`},{label:"Cosplay Ero",value:`${l}/category/cosplay-ero/`},{label:"Cosplay",value:`${l}/category/cosplay/`}],q=[{label:"All",value:""},{label:"24 hours",value:`${l}/24-hours/`},{label:"3 day",value:`${l}/3-day/`},{label:"7 Day",value:`${l}/7-day/`}];function O(e){let t=(0,y.decodeHtmlEntities)(e).trim();return t=t.replace(/\s*[“"']?(?:\d+\s+(?:photos?|videos?|gifs?)(?:,\s*|\s+and\s+)?)+[”"']?\s*$/i,""),t=t.replace(/[“"”]/g,"").trim(),t}function H(e){if(!e)return"/";if(!(0,h.isUrlAbsolute)(e))return e.startsWith("/")?e:`/${e}`;try{let t=new URL(e);return t.origin===l?`${t.pathname}${t.search}`:e}catch{return e}}function J(e,t,n){let r=t||n||`${l}/`,o=r.endsWith("/")?r:`${r}/`;return e<=1?o:o===`${l}/`?`${l}/page/${e}/`:`${o}page/${e}/`}function k(e){let t=[],n=new Set;return e(".large-10 .box-blog-post").each((r,o)=>{let s=e(o),i=s.find(".post-title a, h5 a").first(),a=i.attr("href");if(!a||a==="#")return;let c=H(a);if(n.has(c))return;n.add(c);let v=i.text().trim()||i.attr("title")||"",p=O(v);if(!p)return;let u=s.find(".box-image img").attr("data-src")||s.find(".box-image img").attr("src")||s.find("img").first().attr("src")||S.defaultCover;u&&!(0,h.isUrlAbsolute)(u)&&(u=l+u),t.push({name:p,path:c,cover:u})}),t}function X(e){let t=e('blockquote a[href*="/category/"]').first().text().trim();return t||e("blockquote").first().text().match(/Cosplayer:\s*([^\n\r]+)/i)?.[1]?.trim()||""}function z(e){let t=[];return e(".entry-content").first().find('a.button, a[class*="button"]').each((r,o)=>{let s=e(o),i=s.find("span").first().text().trim()||s.text().trim();if(!/download/i.test(i))return;let a=(s.attr("href")||"").trim();a&&a!=="#"&&t.push({buttonText:i,url:a})}),t.length?`## Download link:
${t.map(r=>`- [${r.buttonText}](${r.url})`).join(`
`)}`:""}function B(e){let t=[],n=new Set;return e(".entry-content").first().find("figure a[href]").each((o,s)=>{let i=e(s).attr("href")?.trim();if(!i||!/\.(webp|jpe?g|png|gif)(\?|$)/i.test(i))return;let a=(0,h.isUrlAbsolute)(i)?i:l+i;n.has(a)||(n.add(a),t.push(a))}),t}function w(e){let t=[],n=new Set;return e(".entry-content").first().find("iframe[src]").each((o,s)=>{let i=e(s).attr("src")?.trim();!i||/googletagmanager/i.test(i)||n.has(i)||(n.add(i),t.push(i))}),t}var x=class extends P{constructor(){super(...arguments);this.id="cosplaytele";this.name="CosplayTele";this.icon="icon.png";this.site=l;this.version="1.1.0";this.contentType=d.MIXED;this.contentWarning=f.NSFW;this.customJS="custom.js";this.customCSS="custom.css";this.imageRequestInit={headers:{Referer:`${l}/`}};this.filters={levelCosplay:{label:"Level Cosplay",type:N.FilterTypes.Picker,value:"",options:M},topCosplay:{label:"Top Cosplay",type:N.FilterTypes.Picker,value:"",options:q}}}async fetchPage(n){return(0,E.fetchText)(n.startsWith("http")?n:`${l}${n}`)}async popularNovels(n,{filters:r}){let o=r.levelCosplay.value,s=r.topCosplay.value,i=J(n,o,s),a=await this.fetchPage(i),c=(0,m.load)(a);return k(c)}async searchNovels(n,r){let o=encodeURIComponent(n.trim()),s=r>1?`${l}/page/${r}/?s=${o}`:`${l}/?s=${o}`,i=await this.fetchPage(s),a=(0,m.load)(i);return k(a)}async parseNovel(n){let r=n.split("#")[0],o=await this.fetchPage(r),s=(0,m.load)(o),i=s("h1.entry-title").first().text().trim()||s('meta[property="og:title"]').attr("content")||"Untitled",a=O(i),c=X(s),v=[];s(".entry-category a, h6.entry-category a").each((K,F)=>{let I=s(F).text().trim();I&&v.push(I)});let p=s('meta[property="og:image"]').attr("content")||s(".entry-content figure img").first().attr("src")||S.defaultCover;p&&!(0,h.isUrlAbsolute)(p)&&(p=l+p);let u=z(s),U=w(s),T=[{name:"Photos",path:`${r}${C}`,chapterNumber:1}];return U.length>0&&T.push({name:"Video",path:`${r}${$}`,chapterNumber:2}),{path:r,name:a,author:c,artist:c,cover:p,genres:v.join(", "),status:W.NovelStatus.Completed,summary:u,chapters:T}}async parseChapter(n){if(n.endsWith(C)){let r=n.slice(0,-C.length),o=await this.fetchPage(r),s=(0,m.load)(o),i=B(s);return i.length?{html:`<div class="cosplaytele-photos">${i.map(c=>`<figure style="margin:0 0 1rem;"><img src="${(0,y.encodeHtmlEntities)(c)}" alt="" style="max-width:100%;height:auto;display:block;margin:0 auto;" loading="lazy"/></figure>`).join(`
`)}</div>`,state:"ready",type:"image"}:{html:"<p>No photos found in this post.</p>",state:"checkpoint",type:"image",noCache:!0,noPrefetch:!0,checkpointMessage:"No photos found in this post."}}if(n.endsWith($)){let r=n.slice(0,-$.length),o=await this.fetchPage(r),s=(0,m.load)(o),i=w(s);return i.length?{html:['<meta name="lnreader-video-mode" content="lazy">',`<div id="cosplaytele-player" data-embeds="${(0,y.encodeHtmlEntities)(JSON.stringify(i))}" style="display:none"></div>`].join(`
`),state:"ready",type:"video",noCache:!0,noPrefetch:!0}:{html:"<p>No embedded video on this post.</p>",state:"checkpoint",type:"video",noCache:!0,noPrefetch:!0,checkpointMessage:"No embedded video on this post."}}throw new Error("Invalid chapter path: "+n)}resolveUrl(n,r){let o=n.split("#")[0];return(0,h.isUrlAbsolute)(o)?o:`${l}${o.startsWith("/")?o:`/${o}`}`}},G=new x;
;if(module.exports.default)exports.default=(function resolvePluginAssets(plugin) {
  for (const field of ['icon', 'customCSS', 'customJS']) {
    const value = plugin[field];
    if (typeof value === 'string' && value && !value.includes('/')) {
      plugin[field] = `src/${plugin.id}/${value}`;
    }
  }
  return plugin;
})(module.exports.default);
