import esbuild from 'esbuild';
import fs from 'fs';
import path from 'path';
import process from 'process';
import fastGlob from 'fast-glob';
const globSync = fastGlob.globSync;

// Find all entry points (index.js) in plugin folders generated by tsc
const entryPointsFiles = globSync('.tsc-out/*/*/index.js', {
  ignore: ['.tsc-out/multisrc/**'],
});

const entryPoints = entryPointsFiles
  .map(ep => {
    // ep format: .tsc-out/language/pluginName/index.js
    const parts = ep.split('/');
    const lang = parts[1];
    const name = parts[2];
    return {
      in: ep,
      out: `${lang}/${name}`,
      lang,
      name,
    };
  })
  .filter(ep => {
    return !fs.existsSync(path.join('plugins', ep.lang, ep.name, 'BROKEN'));
  });

async function build() {
  console.log(`Found ${entryPoints.length} plugins to build.`);
  fs.writeFileSync(
    '.tsc-out/package.json',
    JSON.stringify({ type: 'commonjs' }),
  );

  await esbuild.build({
    entryPoints: entryPoints.map(ep => ({ in: ep.in, out: ep.out })),
    bundle: true,
    minify: true,
    outdir: '.js/plugins',
    format: 'cjs',
    target: 'es5',
    plugins: [
      {
        name: 'external-non-relative',
        setup(build) {
          build.onResolve({ filter: /.*/ }, args => {
            // Allow entry points
            if (args.kind === 'entry-point') return;
            // If it's a relative import, let esbuild bundle it
            if (args.path.startsWith('.')) return;
            // Everything else is external (e.g. '@libs/fetch', 'cheerio')
            return { path: args.path, external: true };
          });
        },
      },
    ],
  });

  console.log('Plugins built successfully.');
}

build().catch(e => {
  console.error('Build failed', e);
  process.exit(1);
});
